runtime: python
env: flex
entrypoint: daphne -b 0.0.0.0 -p $PORT config.asgi:application
runtime_config:
  operating_system: 'ubuntu18'
  runtime_version:  '3.9'

handlers:
  - url: /static
    static_dir: static/
  - url: .*
    script: auto

# Update with Redis instance details
env_variables:
  REDISHOST: '*** RADIS HOST ***'
  REDISPORT: '*** RADIS PORT ***'

beta_settings:
    cloud_sql_instances: *** DB_SQL_CONNECTION_NAME ***

# Update with Serverless VPC Access connector details
network:
  name: default
  session_affinity: true
