runtime: python39
entrypoint: gunicorn -b :$PORT config.wsgi:application

handlers:
  - url: /static
    static_dir: static/
  - url: .*
    script: auto

# Update with Redis instance details
env_variables:
  REDISHOST: '*** RADIS HOST ***'
  REDISPORT: '*** RADIS PORT ***'
# Update with Serverless VPC Access connector details
vpc_access_connector:
  name: 'projects/<PROJECT_ID>/locations/<REGION>/connectors/<CONNECTOR_NAME>'
network:
  session_affinity: true